name: task
description: A new Flutter project.

publish_to: 'none'

version: 0.0.6+0.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  file_picker_writable: ^2.0.0
  file_selector: ^0.8.2
  file_selector_macos: ^0.0.4
  flutter:
    sdk: flutter
  google_fonts: ^2.0.0
  path_provider: ^2.0.1
  path_provider_macos: ^2.0.0
  taskw:
    path: ../taskw
  uuid: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - ../fixture/
    - ../fixture/.task/
    - google_fonts/
