name: task
description: A new Flutter project.

publish_to: 'none'

version: 0.2.7+0.0.0

environment:
  sdk: ^2.17.0
  flutter: ^3.0.0

dependencies:
  built_collection:
  cupertino_icons:
  file_picker_writable:
  file_selector:
  file_selector_linux:
  file_selector_macos:
  file_selector_windows:
  flutter:
    sdk: flutter
  flutter_linkify:
  google_fonts:
  linkify:
  package_info_plus: '>0.0.1'
  path_provider:
  taskc:
    path: ../taskc
  taskj:
    path: ../taskj
  taskw:
    path: ../taskw
  tuple:
  url_launcher:
  uuid:

dependency_overrides:
  win32: '>2.3.1'

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints:
  test:

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/.task/
    - google_fonts/
