name: task
description: A new Flutter project.

publish_to: 'none'

version: 0.0.0+0.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  file_picker:
  google_fonts:
  path_provider:
  taskw:
    path: ../taskw
  uuid:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - ../fixture/
    - ../fixture/.task/
