name: taskc
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0-0 <3.0.0'

dependencies:
  uuid:

dev_dependencies:
  pedantic:
  test:
  test_coverage:
