name: taskc
description: A Taskserver client library
repository: https://github.com/bradyt/taskd-client-dart
version: 0.0.0-alpha.0

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  intl: ^0.16.1
  meta: ^1.2.4
  uuid: ^2.2.2

dev_dependencies:
  pedantic:
  test:
  test_coverage:
