name: taskw
description: Provides Dart libraries for developing a Taskwarrior client to your Taskserver
version: 0.0.0-alpha.0

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

executables:
  mesh: mesh

dependencies:
  args:
  built_collection:
  collection:
  intl:
  petitparser:
  quiver:
  taskc:
    path: ../taskc
  taskj:
    path: ../taskj
  uuid:

dev_dependencies:
  coverage:
  lints:
  test:
  test_cov:
