name: taskw
description: A starting point for Dart libraries or applications.
version: 0.0.0-alpha.0

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection:
  taskc:
    # path: ../../taskd-client-dart
    git:
      url: git://github.com/bradyt/taskd-client-dart.git
      ref: v0.1.0
  uuid: ^3.0.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
