name: test fastlane setup

on:
  pull_request:
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch:

jobs:
  fastlane:
    strategy:
      matrix:
        working-directory: [task/android, task/ios]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: gem install --user-install bundler
    - run: bundle install
      working-directory: ${{ matrix.working-directory }}
    - run: bundle exec fastlane --version
      working-directory: ${{ matrix.working-directory }}
