name: linting

on:
  pull_request:
  push:
    branches-ignore: [main]
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: bradyt/dart-task
    steps:
    - uses: actions/checkout@v2
    - run: echo '/usr/lib/dart/bin' >> $GITHUB_PATH
    - run: dart --disable-analytics
    - run: make format
    - run: make analyze
