name: dart-only CI for taskw

defaults:
  run:
    working-directory: taskw

on:
  pull_request:
  push:
    branches-ignore: [main]
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch:

jobs:
  taskw:
    runs-on: ubuntu-latest
    container:
      image: bradyt/dart-task
    steps:
    - uses: actions/checkout@v2
    - run: dart --disable-analytics
    - run: dart pub get
    - run: dart test
