name: dart-only CI for taskw

defaults:
  run:
    working-directory: taskw

on:
  pull_request:
  push:
    branches-ignore: [main]
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch:

jobs:
  taskw:
    runs-on: ubuntu-latest
    container:
      image: google/dart
    steps:
    - uses: actions/checkout@v2
    - run: dart --disable-analytics
    - run: dart pub get
    - run: >
        dart format \
        $(find . \( -name '*.dart' ! -name '*.g.dart' \)) \
        --fix --output none --set-exit-if-changed --summary none
    - run: dart analyze --fatal-infos
    - run: dart test
