name: beginning of CI that requires taskd on localhost

env:
  PUB_CACHE: '/root/.pub-cache'

defaults:
  run:
    working-directory: taskc

on:
  pull_request:
  push:
    branches-ignore: [main]
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch:

jobs:
  taskd:
    runs-on: ubuntu-latest
    container:
      image: bradyt/dart-task
    steps:
    - uses: actions/checkout@v2
    - run: echo '/usr/lib/dart/bin' >> $GITHUB_PATH
    - run: echo '/root/.pub-cache/bin' >> $GITHUB_PATH

    - run: taskd status
    - run: task --version
    - run: taskd --version

    - run: dart --disable-analytics

    - run: dart pub get --offline
    - run: dart run coverage:test_with_coverage
    - run: genhtml -o coverage coverage/lcov.info
    - run: dlcov -c 50.2
