name: beginning of CI that requires taskd on localhost

defaults:
  run:
    working-directory: taskc

on:
  pull_request:
  push:
    branches-ignore: [main]
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch:

jobs:
  taskd:
    runs-on: ubuntu-latest
    container:
      image: bradyt/dart-task
    steps:
    - uses: actions/checkout@v2
    - run: echo '/sdks/flutter/bin' >> $GITHUB_PATH

    - run: taskd status
    - run: task --version
    - run: taskd --version

    - run: dart --disable-analytics

    - run: dart pub get
    - run: dart test -j 1
